### ISSUE TITLE
Can you safe me one click...

### ISSUE THREAD

**Issue by mktcode** [Taichi-Network/eth-gasnow-extention#4]
...and link this
![image](https://user-images.githubusercontent.com/6792578/117548839-5d4dc600-b037-11eb-81c5-a07640041add.png)
to the website? I know there's a link on the settings page but this would be a little bit more convenient, since I'm doing that several times a day.

**Comment by dzid26** [comment]
This was irking me too, so I added it. 
https://github.com/dzid26/eth-gasnow-extention/releases/tag/0.2.7.1

But they didn't publish the latest source. Seems like they moved here https://github.com/gasnow-engineering/extension-release/releases

**Comment by dzid26** [comment]
Oh, they made it clickable in their latest update. You may want to close this issue @mktcode
