### ISSUE TITLE
Unsafe permissions

### ISSUE THREAD

**Issue by prestonvanloon** [Taichi-Network/eth-gasnow-extention#6]
Why does this extension request permissions to modify my clipboard?

![Screenshot from 2021-05-26 08-29-07](https://user-images.githubusercontent.com/7246818/119668315-b02bc980-bdfc-11eb-9ee3-c9a1a22c8003.png)

**Comment by Phunk87** [comment]
hi @prestonvanloon , v0.3.0 has added wallet function and it needs this permission to copy your eth address into clipboard.

About this new version's code, we will open source as soon as possible.

**Comment by gosuto-inzasheru** [comment]
Same question; "modify data you copy and paste" doesn't sounds safe.

**Comment by mockdot** [comment]
Probably best to consider this extension compromised.

**Comment by SKYLARMIC25** [comment]
ok boss tnx for info im just new learning in self taught

**Comment by SKYLARMIC25** [comment]
ok boss tnx for info im just new learning in self taught

**Comment by Phunk87** [comment]
> Same question; "modify data you copy and paste" doesn't sounds safe.

This sounds really unsafe, and it brings a lot of trouble to users. So we have removed this permission in the version we are reviewing, although it will bring some UX defects.

We really want to achieve the ultimate in UX, but judging from the feedback from the community, we are too anxious. Thank you for your continuous questions. This also allows us to learn how to communicate with users.

**Comment by gosuto-inzasheru** [comment]
Still, can you explain why this extension needs to:
> Read and change all your data on the websites you visit

All I want is an extension which informs me of the current gas price and a quick link to your website.

**Comment by guyunxiang** [comment]
This project has been handed over to other development and maintenance (the new version will support the sending transaction function), this project will no longer be updated.
