### ISSUE TITLE
contributing

### ISSUE THREAD

**Issue by jpangelle** [Taichi-Network/eth-gasnow-extention#7]
Hey I like this project and there a few things I would like to contribute. I am trouble getting the app running though.
In one terminal window, I ran `yarn start:chrome` and then in another window, I ran `yarn start`.

When I launch `localhost:8000`, I get a `ReferenceError: browser is not defined` error:

![image](https://user-images.githubusercontent.com/28536523/122157267-318cdf80-ce30-11eb-8b83-6f5483775402.png)

Are there further steps I need to take to ensure that `browser` is available globally?

**Comment by guyunxiang** [comment]
replace 'browser' to 'chrome'
